name: vladbuff
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch==2.1.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision==0.16.0
  - faiss-gpu
  - pip
  - pip:
    - setuptools<70.0.0
    - xformers==0.0.22.post7
    - pandas==2.1.3
    - prettytable==3.9.0
    - pytorch-lightning==2.1.2
    - pytorch-metric-learning==2.3.0
    - torchmetrics==1.2.0
    - wandb
    - opencv-python
    - natsort
    - matplotlib
    - scikit-image
    - seaborn
    - mpld3
